my_instance_type = "t2.micro"
my_instance_tags = "MyInstance"
my_instance_ami = "ami-08ed5c5dd62794ec0"
aws_access_key = "AKIA3KZTFPFPWTHUYSNC"
aws_secret_key = "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"
aws_region = "us-east-1"